const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('ffmpeg', {
  pickFiles: () => ipcRenderer.invoke('pick-files'),
  pickFfmpeg: () => ipcRenderer.invoke('pick-ffmpeg'),
  setFfmpegPath: (candidate) => ipcRenderer.invoke('set-ffmpeg-path', candidate),
  clearFfmpegPath: () => ipcRenderer.invoke('clear-ffmpeg-path'),
  cpuCount: () => ipcRenderer.invoke('cpu-count'),
  pickDirectory: () => ipcRenderer.invoke('pick-directory'),
  pickAny: () => ipcRenderer.invoke('pick-any'),
  listImages: (directory) => ipcRenderer.invoke('list-images', directory),
  listAllFiles: (directory) => ipcRenderer.invoke('list-all-files', directory),
  streamStart: (payload) => ipcRenderer.invoke('stream-start', payload),
  streamNext: (count) => ipcRenderer.invoke('stream-next', count),
  streamReset: () => ipcRenderer.invoke('stream-reset'),
  listMedia: (directory) => ipcRenderer.invoke('list-media', directory),
  listAudio: (directory) => ipcRenderer.invoke('list-audio', directory),
  checkIntegrity: (payload) => ipcRenderer.invoke('check-integrity', payload),
  repairFile: (payload) => ipcRenderer.invoke('repair-file', payload),
  pathKind: (target) => ipcRenderer.invoke('path-kind', target),
  fileSize: (target) => ipcRenderer.invoke('file-size', target),
  deleteFile: (target) => ipcRenderer.invoke('delete-file', target),
  getConfig: () => ipcRenderer.invoke('get-config'),
  saveSettings: (patch) => ipcRenderer.invoke('save-settings', patch),
  loadSettings: () => ipcRenderer.invoke('load-settings'),
  resetSettings: () => ipcRenderer.invoke('reset-settings'),
  probe: (file) => ipcRenderer.invoke('probe', file),
  capabilities: () => ipcRenderer.invoke('capabilities'),
  run: (args, metadata) => ipcRenderer.invoke('run-ffmpeg', args, metadata),
  onProgress: (callback) => ipcRenderer.on('ffmpeg-progress', (_, progress) => callback(progress)),
  onLog: (callback) => ipcRenderer.on('ffmpeg-log', (_, text) => callback(text))
});
